// COM MEDICAL SERVIS — boshlang'ich kontent.
// Manba: commedical.uz rasmiy sayti (kontaktlar, xizmatlar ro'yxati, uskuna yo'nalishlari).
// seed.js va dev-mock-api.mjs shu fayldan foydalanadi.

/* ------------------------------------------------------------------ */
/*  KATEGORIYALAR — uskuna yo'nalishlari                               */
/* ------------------------------------------------------------------ */
const categories = [
  {
    slug: 'uzi', iconKey: 'uzi', sortOrder: 1, scope: 'BOTH', imageUrl: '/equipment/uzi.jpg',
    nameUz: 'UZI apparatlari', nameRu: 'УЗИ аппараты', nameUzCyrl: 'УЗИ аппаратлари',
    descUz: 'Ultratovush skanerlari va datchiklar. Mindray, Samsung Medison, GE, Siemens, Chison va SonoScape uskunalari bilan ishlaymiz.',
    descRu: 'Ультразвуковые сканеры и датчики. Работаем с Mindray, Samsung Medison, GE, Siemens, Chison и SonoScape.',
    descUzCyrl: 'Ультратовуш сканерлари ва датчиклар. Mindray, Samsung Medison, GE, Siemens, Chison ва SonoScape ускуналари билан ишлаймиз.',
    metaTitleUz: 'UZI apparati ta\'miri va datchik zapchastlari — COM MEDICAL SERVIS',
    metaTitleRu: 'Ремонт УЗИ аппаратов и запчасти к датчикам — COM MEDICAL SERVIS',
    metaTitleUzCyrl: 'УЗИ аппарати таъмири ва датчик запчастлари — COM MEDICAL SERVIS',
    metaDescUz: 'UZI datchigi, monitori va platasi uchun original zapchastlar hamda ta\'mirlash, kalibrovka xizmati. Namangan, kafolat bilan.',
    metaDescRu: 'Оригинальные запчасти для датчиков, мониторов и плат УЗИ, ремонт и калибровка. Наманган, с гарантией.',
    metaDescUzCyrl: 'УЗИ датчиги, монитори ва платаси учун оригинал запчастлар ҳамда таъмирлаш, калибровка хизмати.',
  },
  {
    slug: 'ekg', iconKey: 'ekg', sortOrder: 2, scope: 'BOTH', imageUrl: '/equipment/ekg.jpg',
    nameUz: 'EKG va bemor monitorlari', nameRu: 'ЭКГ и мониторы пациента', nameUzCyrl: 'ЭКГ ва бемор мониторлари',
    descUz: 'Elektrokardiograflar, bemor monitorlari, ularning kabellari, elektrodlari va sarf materiallari.',
    descRu: 'Электрокардиографы, мониторы пациента, кабели, электроды и расходные материалы к ним.',
    descUzCyrl: 'Электрокардиографлар, бемор мониторлари, уларнинг кабеллари, электродлари ва сарф материаллари.',
  },
  {
    slug: 'defibrillator', iconKey: 'defib', sortOrder: 3, scope: 'BOTH', imageUrl: '/equipment/defibrillator.jpg',
    nameUz: 'Defibrillatorlar', nameRu: 'Дефибрилляторы', nameUzCyrl: 'Дефибрилляторлар',
    descUz: 'Defibrillatorlar uchun akkumulyatorlar, elektrod plastinalari, bir martalik elektrodlar va quvvat tekshiruvi.',
    descRu: 'Аккумуляторы, электродные пластины, одноразовые электроды и проверка выходной энергии дефибрилляторов.',
    descUzCyrl: 'Дефибрилляторлар учун аккумуляторлар, электрод пластиналари ва қувват текшируви.',
  },
  {
    slug: 'sterilizatsiya', iconKey: 'sterilizator', sortOrder: 4, scope: 'BOTH', imageUrl: '/equipment/sterilizator.jpg',
    nameUz: 'Sterilizatorlar', nameRu: 'Стерилизаторы', nameUzCyrl: 'Стерилизаторлар',
    descUz: 'Bug\'li avtoklavlar, quruq issiqlik shkaflari, ularning qizdirgichlari, zichlagichlari va klapanlari.',
    descRu: 'Паровые автоклавы, сухожаровые шкафы, ТЭНы, уплотнители и клапаны к ним.',
    descUzCyrl: 'Буғли автоклавлар, қуруқ иссиқлик шкафлари, уларнинг қиздиргичлари ва клапанлари.',
  },
  {
    slug: 'ivl', iconKey: 'ivl', sortOrder: 5, scope: 'BOTH', imageUrl: '/equipment/ivl.jpg',
    nameUz: 'IVL va nafas apparatlari', nameRu: 'ИВЛ и дыхательная аппаратура', nameUzCyrl: 'ИВЛ ва нафас аппаратлари',
    descUz: 'Sun\'iy nafas apparatlari, turbinalar, oqim sensorlari, klapanlar va nafas konturlari.',
    descRu: 'Аппараты ИВЛ, турбины, датчики потока, клапаны и дыхательные контуры.',
    descUzCyrl: 'Сунъий нафас аппаратлари, турбиналар, оқим сенсорлари, клапанлар ва нафас контурлари.',
  },
  {
    slug: 'laboratoriya', iconKey: 'lab', sortOrder: 6, scope: 'BOTH', imageUrl: '/equipment/laboratoriya.jpg',
    nameUz: 'Laboratoriya uskunalari', nameRu: 'Лабораторное оборудование', nameUzCyrl: 'Лаборатория ускуналари',
    descUz: 'Biokimyoviy analizatorlar, sentrifugalar, mikroskoplar, termostatlar va ularga sarf materiallari.',
    descRu: 'Биохимические анализаторы, центрифуги, микроскопы, термостаты и расходники к ним.',
    descUzCyrl: 'Биокимёвий анализаторлар, центрифугалар, микроскоплар, термостатлар ва сарф материаллари.',
  },
  {
    slug: 'nasos', iconKey: 'box', sortOrder: 7, scope: 'BOTH', imageUrl: '/equipment/nasos.jpg',
    nameUz: 'Infuzion nasoslar', nameRu: 'Инфузионные насосы', nameUzCyrl: 'Инфузион насослар',
    descUz: 'Infuzomat va shprits nasoslari: bosim sensorlari, motor-reduktor, akkumulyator va boshqaruv platasi.',
    descRu: 'Инфузоматы и шприцевые насосы: датчики давления, мотор-редуктор, аккумуляторы и платы управления.',
    descUzCyrl: 'Инфузомат ва шприц насослари: босим сенсорлари, мотор-редуктор, аккумулятор ва бошқарув платаси.',
  },
  {
    slug: 'umumiy-servis', iconKey: 'wrench', sortOrder: 8, scope: 'SERVICE',
    nameUz: 'Umumiy texnik xizmat', nameRu: 'Общее техобслуживание', nameUzCyrl: 'Умумий техник хизмат',
    descUz: 'Barcha turdagi tibbiy uskunalarga tegishli xizmatlar: diagnostika, kalibrovka, profilaktika, o\'rnatish.',
    descRu: 'Услуги, применимые ко всем видам медтехники: диагностика, калибровка, профилактика, установка.',
    descUzCyrl: 'Барча турдаги тиббий ускуналарга тегишли хизматлар: диагностика, калибровка, профилактика, ўрнатиш.',
  },
];

/* ------------------------------------------------------------------ */
/*  XIZMATLAR — narxsiz, "nimalar kiradi" ro'yxati bilan               */
/*  (eski saytdagi 6 ta yo'nalish + 2 ta ixtisoslashgan)               */
/* ------------------------------------------------------------------ */
const services = [
  {
    categorySlug: 'umumiy-servis', slug: 'tamirlash', kind: 'SERVICE', isFeatured: true, sortOrder: 1,
    nameUz: 'Ta\'mirlash', nameRu: 'Ремонт', nameUzCyrl: 'Таъмирлаш',
    shortUz: 'Har qanday murakkablikdagi nosozlikni ildizidan hal qilamiz — vaqtinchalik "yamoq" emas.',
    shortRu: 'Устраняем неисправность любой сложности в корне — не временной «заплаткой».',
    shortUzCyrl: 'Ҳар қандай мураккабликдаги носозликни илдизидан ҳал қиламиз — вақтинчалик «ямоқ» эмас.',
    descUz: 'Ta\'mirni hech qachon taxmin bilan boshlamaymiz. Avval nosozlik sababi aniqlanadi, keyin smeta beriladi va faqat siz rozi bo\'lganingizdan keyin ish boshlanadi.\n\nPlata darajasidagi ta\'mirni ham bajaramiz: komponentni almashtirish, kontaktlarni tiklash, quvvat zanjirini qayta tiklash. Butun blokni almashtirish — bu oxirgi variant, chunki u mijozga eng qimmatga tushadi.',
    descRu: 'Мы никогда не начинаем ремонт наугад. Сначала выясняется причина неисправности, затем выдаётся смета, и только после вашего согласия начинается работа.\n\nВыполняем ремонт на уровне платы: замена компонентов, восстановление контактов и цепей питания. Замена блока целиком — последний вариант, потому что он обходится клиенту дороже всего.',
    descUzCyrl: 'Таъмирни ҳеч қачон тахмин билан бошламаймиз. Аввал носозлик сабаби аниқланади, кейин смета берилади ва фақат сиз рози бўлганингиздан кейин иш бошланади.',
    includesUz: [
      'Nosozlik sababini aniqlash va yozma smeta berish',
      'Plata darajasida ta\'mir: komponent almashtirish, kontakt tiklash',
      'Quvvat bloki, ekran, boshqaruv tugmalari va razyomlarni tiklash',
      'Almashtirilgan qismlarni sizga ko\'rsatib topshirish',
      'Ish yakunida to\'liq sinov va test rejimi',
      'Kafolat varaqasi (6–12 oy)',
    ],
    includesRu: [
      'Определение причины неисправности и письменная смета',
      'Ремонт на уровне платы: замена компонентов, восстановление контактов',
      'Восстановление блока питания, экрана, кнопок управления и разъёмов',
      'Демонстрация и передача заменённых деталей клиенту',
      'Полное тестирование по завершении работ',
      'Гарантийный талон (6–12 месяцев)',
    ],
    includesUzCyrl: [
      'Носозлик сабабини аниқлаш ва ёзма смета бериш',
      'Плата даражасида таъмир: компонент алмаштириш, контакт тиклаш',
      'Қувват блоки, экран, бошқарув тугмалари ва разъёмларни тиклаш',
      'Алмаштирилган қисмларни сизга кўрсатиб топшириш',
      'Иш якунида тўлиқ синов ва тест режими',
      'Кафолат варақаси (6–12 ой)',
    ],
    warranty: '6–12 oy',
    keywords: ['tibbiy apparat tamirlash', 'ремонт медицинского оборудования', 'тиббий аппарат таъмирлаш', 'medtexnika remont namangan'],
    metaTitleUz: 'Tibbiy apparatlarni ta\'mirlash — nimalar kiradi | COM MEDICAL SERVIS',
    metaTitleRu: 'Ремонт медицинских аппаратов — что входит | COM MEDICAL SERVIS',
    metaTitleUzCyrl: 'Тиббий аппаратларни таъмирлаш — нималар киради | COM MEDICAL SERVIS',
  },
  {
    categorySlug: 'umumiy-servis', slug: 'diagnostika', kind: 'SERVICE', isFeatured: true, sortOrder: 2,
    nameUz: 'Diagnostika', nameRu: 'Диагностика', nameUzCyrl: 'Диагностика',
    shortUz: 'Aniq tashxis: nima buzilgan, nima uchun buzilgan va uni tuzatish arziydimi.',
    shortRu: 'Точный диагноз: что вышло из строя, почему и стоит ли это чинить.',
    shortUzCyrl: 'Аниқ ташхис: нима бузилган, нима учун бузилган ва уни тузатиш арзийдими.',
    descUz: 'Diagnostika — bu "qarab qo\'yish" emas. Uskunani bosqichma-bosqich tekshiramiz: kirish kuchlanishidan tortib chiquvchi signalgacha.\n\nNatijada siz yozma xulosa olasiz. Unda nafaqat hozirgi nosozlik, balki yaqin oyda ishdan chiqishi mumkin bo\'lgan qismlar ham ko\'rsatiladi — bu keyingi to\'xtashlarning oldini oladi.',
    descRu: 'Диагностика — это не «посмотреть и сказать». Мы проверяем аппарат поэтапно: от входного напряжения до выходного сигнала.\n\nВы получаете письменное заключение. В нём указана не только текущая неисправность, но и узлы, которые могут выйти из строя в ближайшие месяцы — это предотвращает следующие простои.',
    descUzCyrl: 'Диагностика — бу «қараб қўйиш» эмас. Ускунани босқичма-босқич текширамиз: кириш кучланишидан тортиб чиқувчи сигналгача.',
    includesUz: [
      'Tashqi ko\'rik va ishlatish tarixini o\'rganish',
      'Quvvat bloki va kuchlanish darajalarini o\'lchash',
      'Sensor, datchik va kabellarni navbatma-navbat sinash',
      'Dasturiy ta\'minot, xato kodlari va loglarni tekshirish',
      'Yozma xulosa: nosozlik sababi va ta\'mir smetasi',
      'Yaqin kelajakda almashtirish kerak bo\'lgan qismlar ro\'yxati',
    ],
    includesRu: [
      'Внешний осмотр и разбор истории эксплуатации',
      'Замер блока питания и уровней напряжения',
      'Поочерёдная проверка сенсоров, датчиков и кабелей',
      'Проверка прошивки, кодов ошибок и логов',
      'Письменное заключение: причина неисправности и смета',
      'Список узлов, которые потребуют замены в ближайшее время',
    ],
    includesUzCyrl: [
      'Ташқи кўрик ва ишлатиш тарихини ўрганиш',
      'Қувват блоки ва кучланиш даражаларини ўлчаш',
      'Сенсор, датчик ва кабелларни навбатма-навбат синаш',
      'Дастурий таъминот, хато кодлари ва логларни текшириш',
      'Ёзма хулоса: носозлик сабаби ва таъмир сметаси',
      'Яқин келажакда алмаштириш керак бўлган қисмлар рўйхати',
    ],
    leadTimeUz: '1 ish kuni', leadTimeRu: '1 рабочий день', leadTimeUzCyrl: '1 иш куни',
    keywords: ['tibbiy uskuna diagnostikasi', 'диагностика медтехники', 'аппарат диагностикаси'],
  },
  {
    categorySlug: 'umumiy-servis', slug: 'kalibrovka', kind: 'SERVICE', isFeatured: true, sortOrder: 3,
    nameUz: 'Kalibrovka', nameRu: 'Калибровка', nameUzCyrl: 'Калибровка',
    shortUz: 'O\'lchov aniqligini tiklaymiz va natijani protokol bilan rasmiylashtiramiz.',
    shortRu: 'Восстанавливаем точность измерений и оформляем результат протоколом.',
    shortUzCyrl: 'Ўлчов аниқлигини тиклаймиз ва натижани протокол билан расмийлаштирамиз.',
    descUz: 'Uskuna ishlab turgani — u to\'g\'ri o\'lchayapti degani emas. Vaqt o\'tishi bilan sensorlar "suriladi", natijada EKG amplitudasi, IVL hajmi yoki avtoklav harorati haqiqiy qiymatdan chetlashadi.\n\nKalibrovkadan keyin protokol beramiz — u litsenziya va sanitariya tekshiruvlarida so\'raladi.',
    descRu: 'Работающий аппарат — не значит правильно измеряющий. Со временем датчики «уходят», и амплитуда ЭКГ, объём ИВЛ или температура автоклава отклоняются от реальных значений.\n\nПосле калибровки выдаём протокол — его спрашивают при лицензионных и санитарных проверках.',
    descUzCyrl: 'Ускуна ишлаб тургани — у тўғри ўлчаяпти дегани эмас. Калибровкадан кейин протокол берамиз.',
    includesUz: [
      'Etalon asbob bilan joriy ko\'rsatkichlarni solishtirish',
      'Chetlanishni hisoblash va sozlash',
      'EKG uchun 1 mV signal, IVL uchun hajm va bosim, avtoklav uchun harorat/bosim',
      'Takroriy o\'lchov bilan natijani tasdiqlash',
      'Kalibrovka protokoli (tekshiruvlar uchun)',
      'Keyingi kalibrovka sanasi bo\'yicha eslatma',
    ],
    includesRu: [
      'Сравнение текущих показаний с эталонным прибором',
      'Расчёт отклонения и подстройка',
      'Для ЭКГ — сигнал 1 мВ, для ИВЛ — объём и давление, для автоклава — температура/давление',
      'Подтверждение результата повторным замером',
      'Протокол калибровки (для проверок)',
      'Напоминание о дате следующей калибровки',
    ],
    includesUzCyrl: [
      'Эталон асбоб билан жорий кўрсаткичларни солиштириш',
      'Четланишни ҳисоблаш ва созлаш',
      'ЭКГ учун 1 мВ сигнал, ИВЛ учун ҳажм ва босим, автоклав учун ҳарорат/босим',
      'Такрорий ўлчов билан натижани тасдиқлаш',
      'Калибровка протоколи (текширувлар учун)',
      'Кейинги калибровка санаси бўйича эслатма',
    ],
    leadTimeUz: '1–2 ish kuni', leadTimeRu: '1–2 рабочих дня', leadTimeUzCyrl: '1–2 иш куни',
    warranty: '6 oy',
    keywords: ['kalibrovka', 'калибровка медоборудования', 'калибровка ЭКГ', 'o\'lchov aniqligi'],
  },
  {
    categorySlug: 'umumiy-servis', slug: 'profilaktika', kind: 'SERVICE', sortOrder: 4,
    nameUz: 'Profilaktika', nameRu: 'Профилактика', nameUzCyrl: 'Профилактика',
    shortUz: 'Muntazam ko\'rik — nosozlik yuz berishidan oldin uni to\'xtatadi.',
    shortRu: 'Регулярный осмотр останавливает поломку до того, как она случится.',
    shortUzCyrl: 'Мунтазам кўрик — носозлик юз беришидан олдин уни тўхтатади.',
    descUz: 'Tajribamiz shuni ko\'rsatadi: shoshilinch ta\'mirlarning ko\'pini oddiy tozalash va o\'z vaqtida almashtirish bilan oldini olish mumkin edi.\n\nProfilaktikani yiliga 2–4 marta o\'tkazish tavsiya etiladi. Shartnoma asosidagi mijozlar uchun bu jadval bo\'yicha avtomatik bajariladi — o\'zingiz eslab yurishingiz shart emas.',
    descRu: 'Наш опыт показывает: большинство срочных ремонтов можно было предотвратить обычной чисткой и своевременной заменой расходников.\n\nПрофилактику рекомендуем проводить регулярно. Для клиентов по договору она выполняется автоматически — вам не нужно об этом помнить.',
    descUzCyrl: 'Профилактикани йилига 2–4 марта ўтказиш тавсия этилади. Шартнома асосидаги мижозлар учун бу жадвал бўйича автоматик бажарилади.',
    includesUz: [
      'Chang va ifloslikdan tozalash, sovutish tizimini tekshirish',
      'Ventilyator, filtr va sarf materiallarini almashtirish',
      'Kontakt va razyomlarni tozalash, mahkamlash',
      'Akkumulyator sig\'imini o\'lchash',
      'Dasturiy ta\'minotni yangilash (agar mavjud bo\'lsa)',
      'Holat bo\'yicha hisobot va keyingi ko\'rik jadvali',
    ],
    includesRu: [
      'Чистка от пыли и загрязнений, проверка системы охлаждения',
      'Замена вентиляторов, фильтров и расходников',
      'Чистка и протяжка контактов и разъёмов',
      'Замер ёмкости аккумуляторов',
      'Обновление прошивки (при наличии)',
      'Отчёт о состоянии и график следующего осмотра',
    ],
    includesUzCyrl: [
      'Чанг ва ифлосликдан тозалаш, совутиш тизимини текшириш',
      'Вентилятор, филтр ва сарф материалларини алмаштириш',
      'Контакт ва разъёмларни тозалаш, маҳкамлаш',
      'Аккумулятор сиғимини ўлчаш',
      'Дастурий таъминотни янгилаш (агар мавжуд бўлса)',
      'Ҳолат бўйича ҳисобот ва кейинги кўрик жадвали',
    ],
    leadTimeUz: 'Jadval bo\'yicha, 1 ish kuni',
    leadTimeRu: 'По графику, 1 рабочий день',
    leadTimeUzCyrl: 'Жадвал бўйича, 1 иш куни',
    warranty: '3 oy',
    keywords: ['profilaktika', 'профилактика медоборудования', 'texnik korik'],
  },
  {
    categorySlug: 'umumiy-servis', slug: 'ornatish-va-orgatish', kind: 'SERVICE', sortOrder: 5,
    nameUz: 'O\'rnatish va xodimlarni o\'qitish', nameRu: 'Установка и обучение персонала', nameUzCyrl: 'Ўрнатиш ва ходимларни ўқитиш',
    shortUz: 'Yangi uskunani o\'rnatamiz, sozlaymiz va xodimlaringizga ishlashni o\'rgatamiz.',
    shortRu: 'Устанавливаем и настраиваем новое оборудование, обучаем ваш персонал работе с ним.',
    shortUzCyrl: 'Янги ускунани ўрнатамиз, созлаймиз ва ходимларингизга ишлашни ўргатамиз.',
    descUz: 'Yangi apparatning yarim imkoniyati ko\'pincha ishlatilmay qoladi — chunki uni hech kim to\'liq tushuntirib bermagan. Biz o\'rnatishni o\'qitish bilan birga olib boramiz.\n\nO\'qitish amaliy: xodim o\'zi bosadi, o\'zi sozlaydi, biz kuzatamiz va tuzatamiz. Oxirida qisqa yozma yo\'riqnoma qoldiramiz.',
    descRu: 'Половина возможностей нового аппарата часто остаётся неиспользованной — потому что никто их толком не объяснил. Мы совмещаем установку с обучением.\n\nОбучение практическое: сотрудник сам нажимает и настраивает, мы наблюдаем и поправляем. В конце оставляем короткую письменную инструкцию.',
    descUzCyrl: 'Биз ўрнатишни ўқитиш билан бирга олиб борамиз. Ўқитиш амалий: ходим ўзи босади, ўзи созлайди, биз кузатамиз.',
    includesUz: [
      'Uskunani joyiga o\'rnatish va ulash',
      'Elektr tarmog\'i va yerga ulanishni tekshirish',
      'Boshlang\'ich sozlash va til/vaqt parametrlarini kiritish',
      'Xodimlar bilan amaliy mashg\'ulot',
      'Qisqa yozma yo\'riqnoma (o\'zbek yoki rus tilida)',
      'Ishga tushgandan keyin telefon orqali qo\'llab-quvvatlash',
    ],
    includesRu: [
      'Установка и подключение оборудования на месте',
      'Проверка электросети и заземления',
      'Первичная настройка, параметры языка и времени',
      'Практическое занятие с персоналом',
      'Краткая письменная инструкция (на узбекском или русском)',
      'Телефонная поддержка после запуска',
    ],
    includesUzCyrl: [
      'Ускунани жойига ўрнатиш ва улаш',
      'Электр тармоғи ва ерга уланишни текшириш',
      'Бошланғич созлаш ва тил/вақт параметрларини киритиш',
      'Ходимлар билан амалий машғулот',
      'Қисқа ёзма йўриқнома (ўзбек ёки рус тилида)',
      'Ишга тушгандан кейин телефон орқали қўллаб-қувватлаш',
    ],
    leadTimeUz: '1 ish kuni', leadTimeRu: '1 рабочий день', leadTimeUzCyrl: '1 иш куни',
    keywords: ['uskuna ornatish', 'установка медоборудования', 'обучение персонала'],
  },
  {
    categorySlug: 'umumiy-servis', slug: 'zapchast-yetkazib-berish', kind: 'SERVICE', sortOrder: 6,
    nameUz: 'Ehtiyot qismlar yetkazib berish', nameRu: 'Поставка запасных частей', nameUzCyrl: 'Эҳтиёт қисмлар етказиб бериш',
    shortUz: 'Katalogda yo\'q qismni ham topamiz — original yoki tekshirilgan analog.',
    shortRu: 'Найдём и ту деталь, которой нет в каталоге — оригинал или проверенный аналог.',
    shortUzCyrl: 'Каталогда йўқ қисмни ҳам топамиз — оригинал ёки текширилган аналог.',
    descUz: 'Katalogimizda eng ko\'p so\'raladigan pozitsiyalar bor, lekin u hamma narsani qamrab olmaydi. Kerakli qism topilmasa — apparat modelini va zapchast nomini yozing, biz izlab topamiz.\n\nHar bir taklif ikki variantda beriladi: original va sifatli analog. Farqi narxda va kafolat muddatida — tanlash sizniki.',
    descRu: 'В нашем каталоге есть самые ходовые позиции, но он не охватывает всё. Если нужной детали нет — напишите модель аппарата и название запчасти, мы найдём.\n\nКаждое предложение даём в двух вариантах: оригинал и качественный аналог. Разница в цене и сроке гарантии — выбор за вами.',
    descUzCyrl: 'Керакли қисм топилмаса — аппарат моделини ва запчаст номини ёзинг, биз излаб топамиз.',
    includesUz: [
      'Apparat modeli bo\'yicha zapchast mosligini tekshirish',
      'Original va analog variantlarni narxi bilan taqqoslash',
      'Yetkazib berish muddatini aniq aytish',
      'Kelgan qismni o\'rnatishdan oldin sinovdan o\'tkazish',
      'O\'rnatish xizmati (alohida kelishiladi)',
      'Zapchastga kafolat (6–12 oy)',
    ],
    includesRu: [
      'Проверка совместимости запчасти с моделью аппарата',
      'Сравнение оригинала и аналога с указанием цен',
      'Точное указание срока поставки',
      'Тестирование пришедшей детали перед установкой',
      'Услуга установки (согласовывается отдельно)',
      'Гарантия на запчасть (6–12 месяцев)',
    ],
    includesUzCyrl: [
      'Аппарат модели бўйича запчаст мослигини текшириш',
      'Оригинал ва аналог вариантларни нархи билан таққослаш',
      'Етказиб бериш муддатини аниқ айтиш',
      'Келган қисмни ўрнатишдан олдин синовдан ўтказиш',
      'Ўрнатиш хизмати (алоҳида келишилади)',
      'Запчастга кафолат (6–12 ой)',
    ],
    leadTimeUz: 'Omborda bo\'lsa — 1 kun, buyurtma — 7–21 kun',
    leadTimeRu: 'Со склада — 1 день, под заказ — 7–21 день',
    leadTimeUzCyrl: 'Омборда бўлса — 1 кун, буюртма — 7–21 кун',
    warranty: '6–12 oy',
    keywords: ['zapchast yetkazib berish', 'поставка запчастей медтехника', 'эҳтиёт қисм'],
  },
  {
    categorySlug: 'uzi', slug: 'uzi-datchik-tiklash', kind: 'SERVICE', isFeatured: true, sortOrder: 1,
    nameUz: 'UZI datchigini tiklash', nameRu: 'Восстановление УЗИ датчика', nameUzCyrl: 'УЗИ датчигини тиклаш',
    shortUz: 'Yangi datchik sotib olishdan oldin — tiklash imkoniyatini tekshiramiz.',
    shortRu: 'Прежде чем покупать новый датчик — проверяем возможность восстановления.',
    shortUzCyrl: 'Янги датчик сотиб олишдан олдин — тиклаш имкониятини текширамиз.',
    descUz: 'Datchik — skanerning eng qimmat qismi, ba\'zan apparatning yarmiga teng turadi. Shuning uchun uni almashtirishni oxirgi chora deb bilamiz.\n\nAvval to\'liq diagnostika: har bir piezoelement alohida tekshiriladi, kabel va razyomdagi uzilishlar topiladi, korpus germetikligi sinaladi. Natijani suratlar bilan ko\'rsatamiz.',
    descRu: 'Датчик — самая дорогая часть сканера, иногда он стоит как половина аппарата. Поэтому замену считаем крайней мерой.\n\nСначала полная диагностика: каждый пьезоэлемент проверяется отдельно, находятся обрывы в кабеле и разъёме, проверяется герметичность корпуса. Результат показываем с фотографиями.',
    descUzCyrl: 'Датчик — сканернинг энг қиммат қисми. Аввал тўлиқ диагностика: ҳар бир пьезоэлемент алоҳида текширилади, кабель ва разъёмдаги узилишлар топилади.',
    includesUz: [
      'Piezoelementlarni bittalab tekshirish va nosozlarini aniqlash',
      'Akustik linzani almashtirish yoki qayta quyish',
      'Kabel va razyomdagi uzilishlarni tiklash',
      'Korpus germetikligini tiklash, namlikdan tozalash',
      'Test fantomida tasvir sifatini tekshirish',
      'Bajarilgan ish bo\'yicha protokol',
    ],
    includesRu: [
      'Поэлементная проверка пьезоэлементов и выявление дефектных',
      'Замена или переливка акустической линзы',
      'Восстановление обрывов в кабеле и разъёме',
      'Восстановление герметичности корпуса, удаление влаги',
      'Проверка качества изображения на тест-фантоме',
      'Протокол о выполненных работах',
    ],
    includesUzCyrl: [
      'Пьезоэлементларни битталаб текшириш ва носозларини аниқлаш',
      'Акустик линзани алмаштириш ёки қайта қуйиш',
      'Кабель ва разъёмдаги узилишларни тиклаш',
      'Корпус герметиклигини тиклаш, намликдан тозалаш',
      'Тест фантомида тасвир сифатини текшириш',
      'Бажарилган иш бўйича протокол',
    ],
    leadTimeUz: '3–10 ish kuni', leadTimeRu: '3–10 рабочих дней', leadTimeUzCyrl: '3–10 иш куни',
    warranty: '6 oy',
    keywords: ['uzi datchik remont', 'ремонт узи датчика', 'узи датчик таъмирлаш', 'convex probe repair'],
    metaTitleUz: 'UZI datchigini tiklash — nimalar kiradi va qancha vaqt oladi',
    metaTitleRu: 'Восстановление УЗИ датчика — что входит и сколько занимает',
    metaTitleUzCyrl: 'УЗИ датчигини тиклаш — нималар киради ва қанча вақт олади',
  },
  {
    categorySlug: 'ivl', slug: 'ivl-shoshilinch-chaqiruv', kind: 'SERVICE', isFeatured: true, sortOrder: 1,
    nameUz: 'IVL apparatiga shoshilinch chaqiruv', nameRu: 'Срочный выезд к аппарату ИВЛ', nameUzCyrl: 'ИВЛ аппаратига шошилинч чақирув',
    shortUz: 'Reanimatsiyada apparat to\'xtasa — kelishilgan eng qisqa muddatda yetib boramiz.',
    shortRu: 'Если аппарат встал в реанимации — принимаем вызов вне очереди.',
    shortUzCyrl: 'Реанимацияда аппарат тўхтаса — чақирувни навбатсиз қабул қиламиз.',
    descUz: 'IVL apparati kutishga vaqt bermaydi. Shuning uchun eng ko\'p ishlatiladigan qismlar zaxirasini doim tayyor holda saqlaymiz.\n\nIsh yakunida apparat test o\'pkasida sinovdan o\'tkaziladi, barcha rejim parametrlari o\'lchanadi va protokolga yoziladi.',
    descRu: 'Аппарат ИВЛ не даёт времени ждать. Поэтому мы держим наготове запас самых ходовых деталей.\n\nПо окончании работ аппарат проверяется на тестовом лёгком, все параметры режимов измеряются и заносятся в протокол.',
    descUzCyrl: 'ИВЛ аппарати кутишга вақт бермайди. Иш якунида аппарат тест ўпкасида синовдан ўтказилади.',
    includesUz: [
      'Chaqiruvni navbatsiz qabul qilish',
      'Joyida diagnostika va shoshilinch ta\'mir',
      'Turbina, oqim va bosim sensorlarini almashtirish',
      'Ekspirator klapan va kislorod aralashtirgichni sozlash',
      'Test o\'pkasida barcha rejimlarni sinash',
      'Parametrlar protokoli',
    ],
    includesRu: [
      'Приём вызова вне очереди',
      'Диагностика и срочный ремонт на месте',
      'Замена турбины, датчиков потока и давления',
      'Настройка экспираторного клапана и смесителя кислорода',
      'Проверка всех режимов на тестовом лёгком',
      'Протокол параметров',
    ],
    includesUzCyrl: [
      'Чақирувни навбатсиз қабул қилиш',
      'Жойида диагностика ва шошилинч таъмир',
      'Турбина, оқим ва босим сенсорларини алмаштириш',
      'Экспиратор клапан ва кислород аралаштиргични созлаш',
      'Тест ўпкасида барча режимларни синаш',
      'Параметрлар протоколи',
    ],
    warranty: '6 oy',
    keywords: ['ivl remont', 'ремонт ивл', 'сунъий нафас аппарати таъмири'],
  },
];

/* ------------------------------------------------------------------ */
/*  ZAPCHASTLAR                                                        */
/* ------------------------------------------------------------------ */
const spec = (uz, ru, cyrl, value) => ({ labelUz: uz, labelRu: ru, labelUzCyrl: cyrl, value });

const parts = [
  {
    categorySlug: 'uzi', slug: 'convex-datchik-3c5a-mindray', kind: 'PART', partType: 'SENSOR', isFeatured: true, sortOrder: 1,
    nameUz: 'Konveks datchik 3C5A (Mindray uchun)', nameRu: 'Конвексный датчик 3C5A (для Mindray)', nameUzCyrl: 'Конвекс датчик 3C5A (Mindray учун)',
    shortUz: 'Qorin bo\'shlig\'i va akusherlik tekshiruvlari uchun asosiy datchik.',
    shortRu: 'Основной датчик для абдоминальных и акушерских исследований.',
    shortUzCyrl: 'Қорин бўшлиғи ва акушерлик текширувлари учун асосий датчик.',
    descUz: 'Mindray DP-10, DP-20, DP-50 va DC-N seriyali apparatlarga mos konveks datchik. Yetkazib berishdan oldin har bir nusxa stendimizda sinovdan o\'tkaziladi: barcha elementlar ishlashi, tasvirning bir tekisligi va kabel izolyatsiyasi tekshiriladi.\n\nBuyurtma berishdan oldin apparatingizning aniq modelini ayting — razyom turi modelga qarab farq qiladi.',
    descRu: 'Конвексный датчик для аппаратов Mindray серий DP-10, DP-20, DP-50 и DC-N. Перед отправкой каждый экземпляр проходит проверку на нашем стенде: работа всех элементов, равномерность изображения и изоляция кабеля.\n\nПеред заказом уточните точную модель аппарата — тип разъёма зависит от модели.',
    descUzCyrl: 'Mindray DP-10, DP-20, DP-50 ва DC-N серияли аппаратларга мос конвекс датчик. Буюртма беришдан олдин аппаратингизнинг аниқ моделини айтинг.',
    price: 6800000, currency: 'UZS', brand: 'Mindray', model: '3C5A', sku: 'PRB-3C5A-MR',
    originCountry: 'CN', manufacturer: 'Shenzhen Mindray Bio-Medical', condition: 'NEW',
    warranty: '12 oy', inStock: true,
    compatibility: ['Mindray DP-10', 'Mindray DP-20', 'Mindray DP-50', 'Mindray DC-N2', 'Mindray DC-N3'],
    specs: [
      spec('Datchik turi', 'Тип датчика', 'Датчик тури', 'Konveks / Convex'),
      spec('Chastota diapazoni', 'Диапазон частот', 'Частота диапазони', '2.0 – 5.0 MGts'),
      spec('Elementlar soni', 'Количество элементов', 'Элементлар сони', '80'),
      spec('Ko\'rish burchagi', 'Угол обзора', 'Кўриш бурчаги', '60°'),
      spec('Egrilik radiusi', 'Радиус кривизны', 'Эгрилик радиуси', 'R50'),
      spec('Kabel uzunligi', 'Длина кабеля', 'Кабель узунлиги', '2.2 m'),
    ],
    keywords: ['convex datchik narxi', 'купить конвексный датчик mindray', '3c5a датчик'],
    metaTitleUz: 'Konveks datchik 3C5A Mindray — narxi va xarakteristikalari',
    metaTitleRu: 'Конвексный датчик 3C5A Mindray — цена и характеристики',
    metaTitleUzCyrl: 'Конвекс датчик 3C5A Mindray — нархи ва характеристикалари',
  },
  {
    categorySlug: 'uzi', slug: 'linear-datchik-7l4a', kind: 'PART', partType: 'SENSOR', sortOrder: 2,
    nameUz: 'Lineyar datchik 7L4A (yuza organlar uchun)', nameRu: 'Линейный датчик 7L4A (для поверхностных органов)', nameUzCyrl: 'Линеар датчик 7L4A (юза органлар учун)',
    shortUz: 'Qalqonsimon bez, sut bezi, yumshoq to\'qimalar va tomirlar uchun.',
    shortRu: 'Для щитовидной, молочной железы, мягких тканей и сосудов.',
    shortUzCyrl: 'Қалқонсимон без, сут бези, юмшоқ тўқималар ва томирлар учун.',
    descUz: 'Yuqori chastotali lineyar datchik. Yuza joylashgan organlarni tekshirishda tasvir aniqligi asosiy ahamiyatga ega — shuning uchun biz faqat sinovdan o\'tgan nusxalarni sotamiz.',
    descRu: 'Высокочастотный линейный датчик. При исследовании поверхностных органов главное — чёткость изображения, поэтому мы продаём только проверенные экземпляры.',
    descUzCyrl: 'Юқори частотали линеар датчик. Юза жойлашган органларни текширишда тасвир аниқлиги асосий аҳамиятга эга.',
    price: 7400000, currency: 'UZS', brand: 'Mindray', model: '7L4A', sku: 'PRB-7L4A-MR',
    originCountry: 'CN', manufacturer: 'Shenzhen Mindray Bio-Medical', condition: 'NEW',
    warranty: '12 oy', inStock: true,
    compatibility: ['Mindray DP-50', 'Mindray DC-N3', 'Mindray Z60'],
    specs: [
      spec('Datchik turi', 'Тип датчика', 'Датчик тури', 'Lineyar / Linear'),
      spec('Chastota diapazoni', 'Диапазон частот', 'Частота диапазони', '5.0 – 10.0 MGts'),
      spec('Elementlar soni', 'Количество элементов', 'Элементлар сони', '128'),
      spec('Skanerlash kengligi', 'Ширина сканирования', 'Сканерлаш кенглиги', '38 mm'),
      spec('Kabel uzunligi', 'Длина кабеля', 'Кабель узунлиги', '2.2 m'),
    ],
    keywords: ['lineyar datchik', 'линейный датчик узи', '7l4a'],
  },
  {
    categorySlug: 'uzi', slug: 'uzi-monitor-15-lcd', kind: 'PART', partType: 'SCREEN', sortOrder: 3,
    nameUz: 'UZI monitori 15" LCD (matritsa bilan)', nameRu: 'Монитор УЗИ 15" LCD (с матрицей)', nameUzCyrl: 'УЗИ монитори 15" LCD (матрица билан)',
    shortUz: 'Ekranda chiziqlar, dog\'lar yoki yorug\'lik yo\'qolgan bo\'lsa — matritsa almashtiriladi.',
    shortRu: 'Полосы, пятна или пропавшая подсветка на экране — меняется матрица.',
    shortUzCyrl: 'Экранда чизиқлар, доғлар ёки ёруғлик йўқолган бўлса — матрица алмаштирилади.',
    descUz: 'Ekran nosozligi apparatning o\'zi ishlayotgan bo\'lsa ham ishni to\'xtatadi. Ko\'p hollarda butun monitorni emas, faqat matritsani yoki LED yoritgichni almashtirish yetarli — bu ancha arzon.\n\nAvval diagnostika qilamiz: muammo matritsadami, shleyfdami yoki video platadami — aniqlaymiz.',
    descRu: 'Неисправность экрана останавливает работу, даже если сам аппарат исправен. Часто достаточно заменить только матрицу или LED-подсветку, а не монитор целиком — это заметно дешевле.\n\nСначала диагностика: определяем, в чём проблема — в матрице, шлейфе или видеоплате.',
    descUzCyrl: 'Кўп ҳолларда бутун мониторни эмас, фақат матрицани ёки LED ёритгични алмаштириш етарли — бу анча арзон.',
    price: 3200000, currency: 'UZS', brand: 'Universal', model: '15" 4:3 LVDS', sku: 'SCR-15-LVDS',
    originCountry: 'CN', manufacturer: 'BOE Technology', condition: 'NEW',
    warranty: '6 oy', inStock: true,
    compatibility: ['Mindray DP seriya', 'Chison ECO', 'SonoScape A6'],
    specs: [
      spec('Diagonali', 'Диагональ', 'Диагонали', '15 dyuym'),
      spec('Ruxsat', 'Разрешение', 'Рухсат', '1024 × 768'),
      spec('Interfeys', 'Интерфейс', 'Интерфейс', 'LVDS 30-pin'),
      spec('Yorqinlik', 'Яркость', 'Ёрқинлик', '350 cd/m²'),
      spec('Yoritish', 'Подсветка', 'Ёритиш', 'LED'),
    ],
    keywords: ['uzi ekran', 'монитор узи замена', 'lcd matritsa'],
  },
  {
    categorySlug: 'uzi', slug: 'uzi-termoprinter-qogozi', kind: 'PART', partType: 'CONSUMABLE', sortOrder: 4,
    nameUz: 'UZI termoprinter qog\'ozi UPP-110HG', nameRu: 'Термобумага для УЗИ принтера UPP-110HG', nameUzCyrl: 'УЗИ термопринтер қоғози UPP-110HG',
    shortUz: 'Sony UP-895 va mos printerlar uchun original termoqog\'oz.',
    shortRu: 'Оригинальная термобумага для Sony UP-895 и совместимых принтеров.',
    shortUzCyrl: 'Sony UP-895 ва мос принтерлар учун оригинал термоқоғоз.',
    descUz: 'Yuqori zichlikdagi termoqog\'oz — tasvir kontrasti yuqori, vaqt o\'tishi bilan o\'chib ketmaydi. Bir rulon o\'rtacha 200–220 ta surat beradi.',
    descRu: 'Термобумага высокой плотности — высокий контраст, изображение не выцветает со временем. Один рулон в среднем даёт 200–220 снимков.',
    descUzCyrl: 'Юқори зичликдаги термоқоғоз — тасвир контрасти юқори, вақт ўтиши билан ўчиб кетмайди.',
    price: 95000, currency: 'UZS', priceNote: '1 rulon', brand: 'Sony', model: 'UPP-110HG', sku: 'PPR-110HG',
    originCountry: 'JP', manufacturer: 'Sony Corporation', condition: 'NEW',
    warranty: '—', inStock: true, packQty: 1,
    compatibility: ['Sony UP-895MD', 'Sony UP-897MD', 'Mitsubishi P93'],
    specs: [
      spec('Kenglik', 'Ширина', 'Кенглик', '110 mm'),
      spec('Uzunlik', 'Длина', 'Узунлик', '20 m'),
      spec('Turi', 'Тип', 'Тури', 'High Glossy'),
      spec('Rulondagi suratlar', 'Снимков в рулоне', 'Рулондаги суратлар', '~210'),
    ],
    keywords: ['uzi qogoz', 'термобумага узи', 'upp-110hg narxi'],
  },
  {
    categorySlug: 'ekg', slug: 'ekg-bemor-kabeli-10-kanal', kind: 'PART', partType: 'CABLE', isFeatured: true, sortOrder: 1,
    nameUz: 'EKG bemor kabeli, 10 kanalli', nameRu: 'Пациентский кабель ЭКГ, 10-канальный', nameUzCyrl: 'ЭКГ бемор кабели, 10 каналли',
    shortUz: 'Shovqinga chidamli ekranlangan kabel — chiziq "raqs qilmaydi".',
    shortRu: 'Экранированный кабель, устойчивый к наводкам — линия не «пляшет».',
    shortUzCyrl: 'Шовқинга чидамли экранланган кабель — чизиқ «рақс қилмайди».',
    descUz: 'Ko\'p hollarda "apparat buzildi" degan shikoyat aynan kabel bilan bog\'liq bo\'ladi: ichki simlar sinadi va chiziqda shovqin paydo bo\'ladi.\n\nBu kabelda ekranlash ikki qavatli, razyomlar mustahkamlangan. IEC va AHA rang kodlashning ikkala varianti mavjud.',
    descRu: 'Часто жалоба «аппарат сломался» связана именно с кабелем: внутренние жилы ломаются, и на линии появляются наводки.\n\nУ этого кабеля двойное экранирование и усиленные разъёмы. Доступны оба варианта цветовой маркировки — IEC и AHA.',
    descUzCyrl: 'Кўп ҳолларда «аппарат бузилди» деган шикоят айнан кабель билан боғлиқ бўлади. Бу кабелда экранлаш икки қаватли.',
    price: 620000, currency: 'UZS', brand: 'Nihon Kohden', model: 'BJ-901D mos', sku: 'CBL-ECG10',
    originCountry: 'JP', manufacturer: 'Nihon Kohden', condition: 'NEW',
    warranty: '6 oy', inStock: true,
    compatibility: ['Nihon Kohden ECG-1150', 'Mindray BeneHeart R3', 'Edan SE-1200'],
    specs: [
      spec('Kanallar soni', 'Количество каналов', 'Каналлар сони', '10 (12 otvedeniye)'),
      spec('Razyom', 'Разъём', 'Разъём', 'DB-15'),
      spec('Uchlik turi', 'Тип наконечника', 'Учлик тури', 'Banana 4 mm'),
      spec('Rang kodlash', 'Цветовая маркировка', 'Ранг кодлаш', 'IEC / AHA'),
      spec('Uzunlik', 'Длина', 'Узунлик', '3.0 m'),
    ],
    keywords: ['ekg kabel', 'кабель экг купить', 'экг кабели'],
  },
  {
    categorySlug: 'ekg', slug: 'spo2-datchik-kattalar', kind: 'PART', partType: 'SENSOR', sortOrder: 2,
    nameUz: 'SpO₂ datchigi (kattalar uchun, barmoqqa)', nameRu: 'Датчик SpO₂ (взрослый, на палец)', nameUzCyrl: 'SpO₂ датчиги (катталар учун, бармоққа)',
    shortUz: 'Bemor monitorlari uchun qayta ishlatiladigan puls-oksimetriya datchigi.',
    shortRu: 'Многоразовый датчик пульсоксиметрии для мониторов пациента.',
    shortUzCyrl: 'Бемор мониторлари учун қайта ишлатиладиган пульс-оксиметрия датчиги.',
    descUz: 'Silikon korpus, yumshoq qisqich — uzoq monitoring paytida bemorning barmog\'ini bosmaydi. Datchik kelishidan oldin haqiqiy monitorga ulanib tekshiriladi.',
    descRu: 'Силиконовый корпус, мягкая прищепка — не передавливает палец при длительном мониторинге. Перед отправкой датчик проверяется на реальном мониторе.',
    descUzCyrl: 'Силикон корпус, юмшоқ қисқич — узоқ мониторинг пайтида беморнинг бармоғини босмайди.',
    price: 340000, currency: 'UZS', brand: 'Mindray', model: '512F mos', sku: 'SNS-SPO2-AD',
    originCountry: 'CN', manufacturer: 'Shenzhen Mindray Bio-Medical', condition: 'NEW',
    warranty: '6 oy', inStock: true,
    compatibility: ['Mindray iMEC', 'Mindray uMEC', 'Contec CMS8000'],
    specs: [
      spec('Bemor turi', 'Тип пациента', 'Бемор тури', 'Kattalar (>30 kg)'),
      spec('Razyom', 'Разъём', 'Разъём', 'DB-9 / 7-pin'),
      spec('Kabel uzunligi', 'Длина кабеля', 'Кабель узунлиги', '1.1 m'),
      spec('Material', 'Материал', 'Материал', 'Tibbiy silikon'),
    ],
    keywords: ['spo2 datchik', 'датчик пульсоксиметра', 'spo2 сенсор'],
  },
  {
    categorySlug: 'ekg', slug: 'ekg-quvvat-bloki', kind: 'PART', partType: 'POWER', sortOrder: 3,
    nameUz: 'EKG quvvat bloki (adapter 12V 3A)', nameRu: 'Блок питания ЭКГ (адаптер 12В 3А)', nameUzCyrl: 'ЭКГ қувват блоки (адаптер 12V 3A)',
    shortUz: 'Apparat yonmayapti yoki o\'z-o\'zidan o\'chyaptimi — birinchi navbatda shu tekshiriladi.',
    shortRu: 'Аппарат не включается или самопроизвольно выключается — проверяют в первую очередь это.',
    shortUzCyrl: 'Аппарат ёнмаяпти ёки ўз-ўзидан ўчяптими — биринчи навбатда шу текширилади.',
    descUz: 'Tibbiy sinfdagi quvvat bloki: past sizib chiquvchi tok, kuchaytirilgan izolyatsiya. Oddiy maishiy adapter bilan almashtirish mumkin emas — bu bemor xavfsizligiga tegishli.\n\nHar bir blok yuk ostida 2 soat sinovdan o\'tkaziladi.',
    descRu: 'Блок питания медицинского класса: низкий ток утечки, усиленная изоляция. Заменять обычным бытовым адаптером нельзя — это вопрос безопасности пациента.\n\nКаждый блок проходит двухчасовое тестирование под нагрузкой.',
    descUzCyrl: 'Тиббий синфдаги қувват блоки: паст сизиб чиқувчи ток, кучайтирилган изоляция. Оддий маиший адаптер билан алмаштириш мумкин эмас.',
    price: 480000, currency: 'UZS', brand: 'Mean Well', model: 'GSM36B12', sku: 'PWR-12V3A-MED',
    originCountry: 'TR', manufacturer: 'Mean Well Europe', condition: 'NEW',
    warranty: '12 oy', inStock: true,
    compatibility: ['Edan SE-1200', 'Contec ECG-1200G', 'Universal 12V'],
    specs: [
      spec('Chiquvchi kuchlanish', 'Выходное напряжение', 'Чиқувчи кучланиш', '12 V DC'),
      spec('Maks. tok', 'Макс. ток', 'Макс. ток', '3 A'),
      spec('Quvvat', 'Мощность', 'Қувват', '36 W'),
      spec('Xavfsizlik sinfi', 'Класс безопасности', 'Хавфсизлик синфи', 'IEC 60601-1 (2×MOPP)'),
      spec('Sizib chiquvchi tok', 'Ток утечки', 'Сизиб чиқувчи ток', '< 100 µA'),
    ],
    keywords: ['quvvat bloki', 'блок питания медтехника', 'адаптер экг'],
  },
  {
    categorySlug: 'ivl', slug: 'ivl-oqim-sensori', kind: 'PART', partType: 'SENSOR', isFeatured: true, sortOrder: 1,
    nameUz: 'IVL oqim sensori (isitiluvchi sim turi)', nameRu: 'Датчик потока ИВЛ (термоанемометрический)', nameUzCyrl: 'ИВЛ оқим сенсори (иситилувчи сим тури)',
    shortUz: 'Nafas hajmini o\'lchashdagi xatolik shu sensordan boshlanadi.',
    shortRu: 'Ошибки измерения дыхательного объёма начинаются именно с этого датчика.',
    shortUzCyrl: 'Нафас ҳажмини ўлчашдаги хатолик шу сенсордан бошланади.',
    descUz: 'Oqim sensori — IVL apparatining "sezgi organi". U ifloslanganda yoki eskirganda apparat noto\'g\'ri hajm ko\'rsatadi va signal beradi.\n\nSensorni ishlab chiqaruvchi tavsiyasiga ko\'ra vaqti-vaqti bilan almashtirib turish kerak.',
    descRu: 'Датчик потока — «орган чувств» аппарата ИВЛ. При загрязнении или износе аппарат показывает неверный объём и уходит в тревогу.\n\nЗамену рекомендуется проводить по регламенту производителя.',
    descUzCyrl: 'Оқим сенсори — ИВЛ аппаратининг «сезги органи». Сенсорни ишлаб чиқарувчи тавсиясига кўра алмаштириб туриш керак.',
    price: 2450000, currency: 'UZS', brand: 'Dräger', model: 'ISO 8185 mos', sku: 'SNS-FLW-DR',
    originCountry: 'DE', manufacturer: 'Drägerwerk AG', condition: 'NEW',
    warranty: '12 oy', inStock: true,
    compatibility: ['Dräger Savina', 'Dräger Evita 4', 'Hamilton C1'],
    specs: [
      spec('O\'lchash diapazoni', 'Диапазон измерения', 'Ўлчаш диапазони', '0 – 180 l/min'),
      spec('Aniqlik', 'Точность', 'Аниқлик', '±3 %'),
      spec('Sterilizatsiya', 'Стерилизация', 'Стерилизация', 'Avtoklav 134 °C gacha'),
    ],
    keywords: ['ivl sensor', 'датчик потока ивл', 'oqim sensori'],
  },
  {
    categorySlug: 'ivl', slug: 'nafas-konturi-kattalar', kind: 'PART', partType: 'CONSUMABLE', sortOrder: 2,
    nameUz: 'Nafas konturi, kattalar uchun (bir martalik)', nameRu: 'Дыхательный контур, взрослый (одноразовый)', nameUzCyrl: 'Нафас контури, катталар учун (бир марталик)',
    shortUz: 'Suv yig\'gichi va ikkita ulagichli standart kontur.',
    shortRu: 'Стандартный контур с влагосборником и двумя коннекторами.',
    shortUzCyrl: 'Сув йиғгичи ва иккита улагичли стандарт контур.',
    descUz: 'Steril qadoqda, individual o\'ralgan. Konturning ichki yuzasi silliq — kondensat kamroq to\'planadi. Bir bemorga bir kontur qoidasi qat\'iy amal qiladi.',
    descRu: 'В стерильной упаковке, индивидуально запакован. Внутренняя поверхность гладкая — меньше скапливается конденсат. Строго один контур на одного пациента.',
    descUzCyrl: 'Стерил қадоқда, индивидуал ўралган. Бир беморга бир контур қоидаси қатъий амал қилади.',
    price: 78000, currency: 'UZS', priceNote: '1 dona', brand: 'Intersurgical', model: 'Smoothbore', sku: 'CRC-AD-22',
    originCountry: 'GB', manufacturer: 'Intersurgical Ltd', condition: 'NEW',
    warranty: '—', inStock: true, packQty: 1,
    compatibility: ['Universal 22 mm'],
    specs: [
      spec('Diametr', 'Диаметр', 'Диаметр', '22 mm'),
      spec('Uzunlik', 'Длина', 'Узунлик', '1.6 m'),
      spec('Suv yig\'gich', 'Влагосборник', 'Сув йиғгич', 'Bor (2 ta)'),
      spec('Sterillik', 'Стерильность', 'Стериллик', 'EO steril, bir martalik'),
    ],
    keywords: ['nafas konturi', 'дыхательный контур купить'],
  },
  {
    categorySlug: 'defibrillator', slug: 'defibrillator-akkumulyatori-li-ion', kind: 'PART', partType: 'POWER', isFeatured: true, sortOrder: 1,
    nameUz: 'Defibrillator akkumulyatori Li-Ion 11.1V', nameRu: 'Аккумулятор дефибриллятора Li-Ion 11.1В', nameUzCyrl: 'Дефибриллятор аккумулятори Li-Ion 11.1V',
    shortUz: 'Eski batareya bilan apparat razryadga sekin tayyorlanadi — bu qimmatga tushadi.',
    shortRu: 'Со старой батареей аппарат медленно набирает заряд — это дорого обходится.',
    shortUzCyrl: 'Эски батарея билан аппарат разрядга секин тайёрланади — бу қимматга тушади.',
    descUz: 'Batareyani har 2–3 yilda almashtirish tavsiya etiladi, hatto tashqi ko\'rinishi yaxshi bo\'lsa ham. Li-Ion element vaqt o\'tishi bilan sig\'imini yo\'qotadi va bu razryad tayyorlash vaqtida seziladi.\n\nBiz sotadigan har bir batareya sig\'im testidan o\'tkaziladi — natijasi qadoqda yoziladi.',
    descRu: 'Батарею рекомендуется менять каждые 2–3 года, даже если внешне она в порядке. Li-Ion элемент со временем теряет ёмкость, и это заметно по времени набора заряда.\n\nКаждая продаваемая нами батарея проходит тест ёмкости — результат указан на упаковке.',
    descUzCyrl: 'Батареяни ҳар 2–3 йилда алмаштириш тавсия этилади. Ҳар бир батарея сиғим тестидан ўтказилади.',
    price: 2100000, currency: 'UZS', brand: 'Mindray', model: 'LI23S002A mos', sku: 'BAT-DEF-111',
    originCountry: 'CN', manufacturer: 'Shenzhen Mindray Bio-Medical', condition: 'NEW',
    warranty: '12 oy', inStock: true,
    compatibility: ['Mindray BeneHeart D3', 'Mindray BeneHeart D6'],
    specs: [
      spec('Kimyoviy tur', 'Тип химии', 'Кимёвий тур', 'Li-Ion'),
      spec('Kuchlanish', 'Напряжение', 'Кучланиш', '11.1 V'),
      spec('Sig\'im', 'Ёмкость', 'Сиғим', '4400 mAh'),
      spec('Razryadlar soni', 'Количество разрядов', 'Разрядлар сони', '~90 (to\'liq zaryaddan)'),
      spec('Sikllar resursi', 'Ресурс циклов', 'Цикллар ресурси', '300+'),
    ],
    keywords: ['defibrillator batareya', 'аккумулятор дефибриллятора', 'дефибриллятор батареяси'],
  },
  {
    categorySlug: 'defibrillator', slug: 'defibrillator-elektrod-plastinalari', kind: 'PART', partType: 'CABLE', sortOrder: 2,
    nameUz: 'Defibrillator elektrod plastinalari (kattalar + bolalar)', nameRu: 'Электродные пластины дефибриллятора (взрослые + детские)', nameUzCyrl: 'Дефибриллятор электрод пластиналари (катталар + болалар)',
    shortUz: 'Ikki o\'lchamli to\'plam: kattalar plastinasi ostida bolalar plastinasi.',
    shortRu: 'Комплект двух размеров: детская пластина под взрослой.',
    shortUzCyrl: 'Икки ўлчамли тўплам: катталар пластинаси остида болалар пластинаси.',
    descUz: 'Plastinalar tok o\'tkazuvchi qatlami eskirganda razryadni to\'liq yetkazmaydi va bemor terisini kuydirishi mumkin. Ko\'zdan kechirishni har profilaktikada o\'tkazish kerak.',
    descRu: 'При износе токопроводящего слоя пластины не передают разряд полностью и могут вызвать ожог кожи пациента. Осмотр нужно проводить при каждой профилактике.',
    descUzCyrl: 'Пластиналар ток ўтказувчи қатлами эскирганда разрядни тўлиқ етказмайди ва бемор терисини куйдириши мумкин.',
    price: 1450000, currency: 'UZS', brand: 'Mindray', model: 'D-series mos', sku: 'PAD-DEF-AD',
    originCountry: 'CN', manufacturer: 'Shenzhen Mindray Bio-Medical', condition: 'NEW',
    warranty: '6 oy', inStock: false,
    compatibility: ['Mindray BeneHeart D3', 'Mindray BeneHeart D6'],
    specs: [
      spec('To\'plam', 'Комплект', 'Тўплам', '2 dona (kattalar + bolalar)'),
      spec('Kattalar yuzasi', 'Площадь взрослой', 'Катталар юзаси', '82 cm²'),
      spec('Bolalar yuzasi', 'Площадь детской', 'Болалар юзаси', '28 cm²'),
      spec('Kabel uzunligi', 'Длина кабеля', 'Кабель узунлиги', '2.0 m'),
    ],
    keywords: ['defibrillator elektrod', 'электроды дефибриллятора'],
  },
  {
    categorySlug: 'sterilizatsiya', slug: 'avtoklav-eshik-zichlagichi', kind: 'PART', partType: 'MECHANICAL', sortOrder: 1,
    nameUz: 'Avtoklav eshigi zichlagichi (silikon)', nameRu: 'Уплотнитель двери автоклава (силикон)', nameUzCyrl: 'Автоклав эшиги зичлагичи (силикон)',
    shortUz: 'Bosim ushlamayotgan avtoklavning eng ko\'p uchraydigan sababi.',
    shortRu: 'Самая частая причина, почему автоклав не держит давление.',
    shortUzCyrl: 'Босим ушламаётган автоклавнинг энг кўп учрайдиган сабаби.',
    descUz: 'Zichlagich issiqlik va bug\' ta\'sirida qattiqlashadi va yorilib ketadi. Uni almashtirish — eng arzon va eng tez ta\'mir. Yiliga bir marta ko\'zdan kechirish tavsiya etiladi.',
    descRu: 'Уплотнитель твердеет и трескается от жара и пара. Его замена — самый дешёвый и быстрый ремонт. Осмотр рекомендуется раз в год.',
    descUzCyrl: 'Зичлагич иссиқлик ва буғ таъсирида қаттиқлашади ва ёрилиб кетади. Уни алмаштириш — энг арзон ва энг тез таъмир.',
    price: 430000, currency: 'UZS', brand: 'Tuttnauer', model: '2540 mos', sku: 'SEA-AUT-2540',
    originCountry: 'IL', manufacturer: 'Tuttnauer', condition: 'NEW',
    warranty: '6 oy', inStock: true,
    compatibility: ['Tuttnauer 2540 EA', 'Tuttnauer 3870', 'SciCan Statim mos'],
    specs: [
      spec('Material', 'Материал', 'Материал', 'Tibbiy silikon'),
      spec('Ishchi harorat', 'Рабочая температура', 'Ишчи ҳарорат', '-40 … +230 °C'),
      spec('Ichki diametr', 'Внутренний диаметр', 'Ички диаметр', '245 mm'),
      spec('Xizmat muddati', 'Срок службы', 'Хизмат муддати', '~1500 sikl'),
    ],
    keywords: ['avtoklav zichlagich', 'уплотнитель автоклава'],
  },
  {
    categorySlug: 'sterilizatsiya', slug: 'avtoklav-qizdirgich-teni', kind: 'PART', partType: 'POWER', sortOrder: 2,
    nameUz: 'Avtoklav qizdirgichi (TEN 1500 W)', nameRu: 'ТЭН автоклава (1500 Вт)', nameUzCyrl: 'Автоклав қиздиргичи (ТЭН 1500 Вт)',
    shortUz: 'Sikl juda uzoq davom etsa yoki harorat yetmasa — odatda qizdirgich aybdor.',
    shortRu: 'Если цикл длится слишком долго или не набирается температура — обычно виноват ТЭН.',
    shortUzCyrl: 'Цикл жуда узоқ давом этса ёки ҳарорат етмаса — одатда қиздиргич айбдор.',
    descUz: 'Nerjaveyka qobiqli qizdirgich element. Suv sifati yomon bo\'lsa uning yuzasida qatlam yig\'iladi, issiqlik uzatish yomonlashadi va element kuyadi.\n\nAlmashtirishda qazonni ham tozalashni tavsiya qilamiz — aks holda yangi element ham tez ishdan chiqadi.',
    descRu: 'Нагревательный элемент в нержавеющей оболочке. При плохом качестве воды на нём образуется накипь, теплоотдача падает и элемент перегорает.\n\nПри замене рекомендуем также очистить камеру — иначе новый элемент быстро выйдет из строя.',
    descUzCyrl: 'Нержавейка қобиқли қиздиргич элемент. Алмаштиришда қозонни ҳам тозалашни тавсия қиламиз.',
    price: 690000, currency: 'UZS', brand: 'Universal', model: '1500W M14', sku: 'HTR-AUT-1500',
    originCountry: 'TR', manufacturer: 'Elektroteks', condition: 'NEW',
    warranty: '6 oy', inStock: true,
    compatibility: ['Tuttnauer 2540', 'DGM avtoklavlari', 'Universal M14'],
    specs: [
      spec('Quvvat', 'Мощность', 'Қувват', '1500 W'),
      spec('Kuchlanish', 'Напряжение', 'Кучланиш', '220 V'),
      spec('Rezba', 'Резьба', 'Резьба', 'M14'),
      spec('Material', 'Материал', 'Материал', 'AISI 304'),
    ],
    keywords: ['avtoklav ten', 'тэн автоклава', 'qizdirgich element'],
  },
  {
    categorySlug: 'laboratoriya', slug: 'sentrifuga-rotori-8x15', kind: 'PART', partType: 'MECHANICAL', sortOrder: 1,
    nameUz: 'Sentrifuga rotori 8×15 ml', nameRu: 'Ротор центрифуги 8×15 мл', nameUzCyrl: 'Центрифуга ротори 8×15 мл',
    shortUz: 'Burchakli rotor, 15 ml probirkalar uchun 8 uya.',
    shortRu: 'Угловой ротор, 8 гнёзд под пробирки 15 мл.',
    shortUzCyrl: 'Бурчакли ротор, 15 мл пробиркалар учун 8 уя.',
    descUz: 'Alyuminiy qotishmadan, anodlangan qoplama bilan — kimyoviy ta\'sirga chidamli. Rotor balanslangan holda yetkazib beriladi, sertifikati bilan.',
    descRu: 'Из алюминиевого сплава с анодированным покрытием — устойчив к химическому воздействию. Ротор поставляется отбалансированным, с сертификатом.',
    descUzCyrl: 'Алюминий қотишмадан, анодланган қоплама билан. Ротор баланслаган ҳолда етказиб берилади.',
    price: 1650000, currency: 'UZS', brand: 'Hettich', model: '1424 mos', sku: 'ROT-8X15',
    originCountry: 'DE', manufacturer: 'Andreas Hettich GmbH', condition: 'NEW',
    warranty: '12 oy', inStock: false,
    compatibility: ['Hettich EBA 20', 'Hettich EBA 200'],
    specs: [
      spec('Uyalar soni', 'Количество гнёзд', 'Уялар сони', '8'),
      spec('Probirka hajmi', 'Объём пробирки', 'Пробирка ҳажми', '15 ml'),
      spec('Maks. tezlik', 'Макс. скорость', 'Макс. тезлик', '6000 ayl/min'),
      spec('Maks. RCF', 'Макс. RCF', 'Макс. RCF', '4025 g'),
      spec('Material', 'Материал', 'Материал', 'Anodlangan alyuminiy'),
    ],
    keywords: ['sentrifuga rotor', 'ротор центрифуги купить'],
  },
  {
    categorySlug: 'nasos', slug: 'infuzion-nasos-bosim-sensori', kind: 'PART', partType: 'SENSOR', sortOrder: 1,
    nameUz: 'Infuzion nasos bosim sensori', nameRu: 'Датчик давления инфузионного насоса', nameUzCyrl: 'Инфузион насос босим сенсори',
    shortUz: '"Okklyuziya" signali sababsiz chiqaversa — sensor eskirgan.',
    shortRu: 'Если тревога «окклюзия» срабатывает без причины — датчик изношен.',
    shortUzCyrl: '«Окклюзия» сигнали сабабсиз чиқаверса — сенсор эскирган.',
    descUz: 'Bosim sensori infuzion tizimdagi tiqilishni aniqlaydi. U noto\'g\'ri ishlaganda apparat yo bemorni behuda bezovta qiladi, yo haqiqiy tiqilishni sezmaydi — ikkalasi ham xavfli.',
    descRu: 'Датчик давления определяет окклюзию в инфузионной системе. При его неисправности аппарат либо тревожит зря, либо не замечает реальную закупорку — опасно и то, и другое.',
    descUzCyrl: 'Босим сенсори инфузион тизимдаги тиқилишни аниқлайди. У нотўғри ишлаганда аппарат хавфли ҳолатга тушади.',
    price: 890000, currency: 'UZS', brand: 'B.Braun', model: 'Infusomat mos', sku: 'SNS-PRS-INF',
    originCountry: 'DE', manufacturer: 'B. Braun Melsungen AG', condition: 'NEW',
    warranty: '12 oy', inStock: true,
    compatibility: ['B.Braun Infusomat Space', 'Perfusor Space'],
    specs: [
      spec('O\'lchash diapazoni', 'Диапазон измерения', 'Ўлчаш диапазони', '0 – 1200 mmHg'),
      spec('Aniqlik', 'Точность', 'Аниқлик', '±2 %'),
      spec('Ishchi harorat', 'Рабочая температура', 'Ишчи ҳарорат', '+5 … +40 °C'),
    ],
    keywords: ['infuzion nasos sensor', 'датчик давления инфузомата'],
  },
];

/* ------------------------------------------------------------------ */
/*  SAYT SOZLAMALARI — commedical.uz dagi real ma'lumotlar             */
/* ------------------------------------------------------------------ */
export const siteSettings = {
  id: 'main',
  siteNameUz: 'COM MEDICAL SERVIS',
  siteNameRu: 'COM MEDICAL SERVIS',
  siteNameUzCyrl: 'COM MEDICAL SERVIS',

  taglineUz: 'Tibbiy apparatlarni ta\'mirlash, diagnostika, kalibrovka va original ehtiyot qismlar bilan ta\'minlash. Avval smeta — keyin ta\'mir, yashirin to\'lovsiz.',
  taglineRu: 'Ремонт, диагностика и калибровка медицинских аппаратов, поставка оригинальных запчастей. Сначала смета — потом ремонт, без скрытых платежей.',
  taglineUzCyrl: 'Тиббий аппаратларни таъмирлаш, диагностика, калибровка ва оригинал эҳтиёт қисмлар билан таъминлаш. Аввал смета — кейин таъмир, яширин тўловсиз.',

  aboutUz: 'COM MEDICAL SERVIS — Namangandagi tibbiy texnika servisi. Klinikalar, tug\'ruqxonalar, xususiy shifoxonalar va laboratoriyalarning uskunalarini ishga qaytaramiz: UZI, EKG, defibrillator, sterilizator, IVL, laboratoriya asboblari va infuzion nasoslar.',
  aboutRu: 'COM MEDICAL SERVIS — сервис медтехники в Намангане. Возвращаем в строй оборудование клиник, роддомов, частных медцентров и лабораторий: УЗИ, ЭКГ, дефибрилляторы, стерилизаторы, ИВЛ, лабораторные приборы и инфузионные насосы.',
  aboutUzCyrl: 'COM MEDICAL SERVIS — Наманганда тиббий техника сервиси. Клиникалар, туғруқхоналар, хусусий шифохоналар ва лабораторияларнинг ускуналарини ишга қайтарамиз.',

  addressUz: 'Namangan viloyati, Namangan sh., Yangi Namangan tumani, Go\'zal MFY, Go\'zal massivi, 2-d uy',
  addressRu: 'Наманганская обл., г. Наманган, Янги Наманганский р-н, МФЙ Гўзал, массив Гўзал, дом 2-д',
  addressUzCyrl: 'Наманган вилояти, Наманган ш., Янги Наманган тумани, Гўзал МФЙ, Гўзал массиви, 2-д уй',

  phones: [{ label: 'Asosiy', value: '+998902758883', isPrimary: true }],
  socials: [],
  emails: ['mirzayev@mail.ru'],

  metaTitleUz: 'COM MEDICAL SERVIS — tibbiy apparatlar servisi va zapchastlar | Namangan',
  metaTitleRu: 'COM MEDICAL SERVIS — сервис медицинских аппаратов и запчасти | Наманган',
  metaTitleUzCyrl: 'COM MEDICAL SERVIS — тиббий аппаратлар сервиси ва запчастлар | Наманган',
  metaDescUz: 'UZI, EKG, defibrillator, sterilizator, IVL va laboratoriya uskunalarini ta\'mirlash, diagnostika, kalibrovka. Original zapchastlar: xarakteristikalar, ishlab chiqarilgan davlat, narx. Namangan, kafolat 6–12 oy.',
  metaDescRu: 'Ремонт, диагностика и калибровка УЗИ, ЭКГ, дефибрилляторов, стерилизаторов, ИВЛ и лабораторного оборудования. Оригинальные запчасти: характеристики, страна производства, цена. Наманган, гарантия 6–12 месяцев.',
  metaDescUzCyrl: 'УЗИ, ЭКГ, дефибриллятор, стерилизатор, ИВЛ ва лаборатория ускуналарини таъмирлаш, диагностика, калибровка. Оригинал запчастлар. Наманган, кафолат 6–12 ой.',
};

export { categories, services, parts };
